### ISSUE TITLE
Inserir notificações na pipeline

### ISSUE THREAD

**Issue by arbgjr** [arbgjr/BADGE#17]
Para integrar um sistema de notificações via HTTP trigger na sua pipeline do GitHub Actions, você pode usar as funcionalidades de webhook ou uma API de terceiros para enviar notificações. Essas notificações podem incluir erros, warnings, informações e sucessos, com um indicativo do tipo de aviso. Aqui está um exemplo de como você pode configurar isso:

### 1. Preparando o Webhook ou API de Notificações

Primeiro, você precisa de um endpoint de webhook ou uma API de terceiros que possa receber requisições HTTP e enviar notificações. Ferramentas como Slack, Microsoft Teams, ou serviços de webhook personalizados podem ser usados. Configure um endpoint que possa aceitar requisições POST com um payload JSON.

### 2. Criando a Seção de Notificações na Pipeline

Você vai adicionar um novo job ou step em sua pipeline do GitHub Actions para enviar notificações. Este job ou step será responsável por fazer uma requisição HTTP para o seu endpoint de notificações com os detalhes necessários.

Aqui está um exemplo de como você pode configurar um step de notificações no final da sua pipeline:

```yaml
jobs:
  # ... seus outros jobs ...

  notify:
    runs-on: ubuntu-latest
    if: always() # Isso garante que a notificação será enviada independentemente do sucesso ou falha dos jobs anteriores
    needs: [seus_jobs_anteriores] # Substitua com os nomes dos jobs dos quais esta notificação depende
    steps:
      - name: Enviar Notificação
        run: |
          curl -X POST ${{ secrets.NOTIFICATION_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{"status": "${{ job.status }}", "message": "Sua mensagem aqui", "tipo": "${{ job.status == 'success' ? 'Sucesso' : (job.status == 'failure' ? 'Erro' : 'Informação') }}"}'
```

### 3. Personalizando as Mensagens de Notificação

No exemplo acima, a mensagem de notificação é enviada via `curl` para um endpoint definido em seus Secrets do GitHub (`NOTIFICATION_WEBHOOK_URL`). Você deve personalizar o payload JSON (`-d`) para incluir as informações que deseja comunicar, como o status do job e mensagens específicas.

### 4. Teste e Ajuste

Teste a pipeline para garantir que as notificações estão sendo enviadas corretamente. Dependendo da ferramenta ou serviço que você está usando para receber as notificações, você pode precisar ajustar o formato do payload ou os cabeçalhos da requisição.

### 5. Segurança e Privacidade

Garanta que nenhuma informação sensível seja enviada nas notificações. Use Secrets do GitHub para armazenar tokens de autenticação ou URLs de webhook.

### Conclusão

Esta configuração permite que você envie notificações automatizadas sobre o status da sua pipeline, incluindo erros, warnings, informações e sucessos. Ajuste o payload e a lógica conforme necessário para atender às necessidades específicas do seu projeto e da ferramenta de notificação escolhida.
